# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import event_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_event.proto',
  package='',
  serialized_pb='\n\x13message_event.proto\x1a\x0b\x65vent.proto\"5\n\x0cMessageEvent\x12\x0e\n\x06sys_id\x18\x01 \x02(\t\x12\x15\n\x05\x65vent\x18\x02 \x03(\x0b\x32\x06.Event')




_MESSAGEEVENT = _descriptor.Descriptor(
  name='MessageEvent',
  full_name='MessageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_id', full_name='MessageEvent.sys_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='MessageEvent.event', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=89,
)

_MESSAGEEVENT.fields_by_name['event'].message_type = event_pb2._EVENT
DESCRIPTOR.message_types_by_name['MessageEvent'] = _MESSAGEEVENT

class MessageEvent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEEVENT

  # @@protoc_insertion_point(class_scope:MessageEvent)


# @@protoc_insertion_point(module_scope)
