# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_hello_ok.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_hello_ok.proto',
  package='',
  serialized_pb='\n\x16message_hello_ok.proto\" \n\x0eMessageHelloOK\x12\x0e\n\x06sys_id\x18\x01 \x02(\t')




_MESSAGEHELLOOK = _descriptor.Descriptor(
  name='MessageHelloOK',
  full_name='MessageHelloOK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_id', full_name='MessageHelloOK.sys_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['MessageHelloOK'] = _MESSAGEHELLOOK

class MessageHelloOK(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEHELLOOK

  # @@protoc_insertion_point(class_scope:MessageHelloOK)


# @@protoc_insertion_point(module_scope)
