# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import node_data_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_hello.proto',
  package='',
  serialized_pb='\n\x13message_hello.proto\x1a\x0fnode_data.proto\"=\n\x0cMessageHello\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1c\n\tnode_data\x18\x02 \x02(\x0b\x32\t.NodeData')




_MESSAGEHELLO = _descriptor.Descriptor(
  name='MessageHello',
  full_name='MessageHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='MessageHello.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_data', full_name='MessageHello.node_data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=101,
)

_MESSAGEHELLO.fields_by_name['node_data'].message_type = node_data_pb2._NODEDATA
DESCRIPTOR.message_types_by_name['MessageHello'] = _MESSAGEHELLO

class MessageHello(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEHELLO

  # @@protoc_insertion_point(class_scope:MessageHello)


# @@protoc_insertion_point(module_scope)
