# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_hello.proto',
  package='',
  serialized_pb='\n\x13message_hello.proto\"\x88\x02\n\x0cMessageHello\x12\x0e\n\x06sys_id\x18\x01 \x01(\t\x12-\n\x0bsystem_info\x18\x02 \x02(\x0b\x32\x18.MessageHello.SystemInfo\x1a\xb8\x01\n\nSystemInfo\x12\x33\n\x08language\x18\x01 \x02(\x0e\x32!.MessageHello.SystemInfo.Language\x12\x18\n\x10language_version\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\r\n\x05uname\x18\x04 \x01(\t\x12\x11\n\texec_path\x18\x05 \x01(\t\"\'\n\x08Language\x12\n\n\x06PYTHON\x10\x00\x12\x08\n\x04JAVA\x10\x01\x12\x05\n\x01\x43\x10\x02')



_MESSAGEHELLO_SYSTEMINFO_LANGUAGE = _descriptor.EnumDescriptor(
  name='Language',
  full_name='MessageHello.SystemInfo.Language',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PYTHON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JAVA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=249,
  serialized_end=288,
)


_MESSAGEHELLO_SYSTEMINFO = _descriptor.Descriptor(
  name='SystemInfo',
  full_name='MessageHello.SystemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='MessageHello.SystemInfo.language', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language_version', full_name='MessageHello.SystemInfo.language_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='MessageHello.SystemInfo.hostname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uname', full_name='MessageHello.SystemInfo.uname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_path', full_name='MessageHello.SystemInfo.exec_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGEHELLO_SYSTEMINFO_LANGUAGE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=288,
)

_MESSAGEHELLO = _descriptor.Descriptor(
  name='MessageHello',
  full_name='MessageHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_id', full_name='MessageHello.sys_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_info', full_name='MessageHello.system_info', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGEHELLO_SYSTEMINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=288,
)

_MESSAGEHELLO_SYSTEMINFO.fields_by_name['language'].enum_type = _MESSAGEHELLO_SYSTEMINFO_LANGUAGE
_MESSAGEHELLO_SYSTEMINFO.containing_type = _MESSAGEHELLO;
_MESSAGEHELLO_SYSTEMINFO_LANGUAGE.containing_type = _MESSAGEHELLO_SYSTEMINFO;
_MESSAGEHELLO.fields_by_name['system_info'].message_type = _MESSAGEHELLO_SYSTEMINFO
DESCRIPTOR.message_types_by_name['MessageHello'] = _MESSAGEHELLO

class MessageHello(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class SystemInfo(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MESSAGEHELLO_SYSTEMINFO

    # @@protoc_insertion_point(class_scope:MessageHello.SystemInfo)
  DESCRIPTOR = _MESSAGEHELLO

  # @@protoc_insertion_point(class_scope:MessageHello)


# @@protoc_insertion_point(module_scope)
