# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_event.proto',
  package='',
  serialized_pb='\n\x13message_event.proto\"\xd9\x01\n\x0cMessageEvent\x12\x0e\n\x06sys_id\x18\x01 \x02(\t\x12\"\n\x05\x65vent\x18\x02 \x03(\x0b\x32\x13.MessageEvent.Event\x1a\x63\n\x05\x45vent\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x17.MessageEvent.EventType:\x05\x42\x41SIC\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\x01\x12\x0b\n\x03\x61rg\x18\x03 \x03(\t\"0\n\tEventType\x12\t\n\x05\x42\x41SIC\x10\x00\x12\x0b\n\x07SECTION\x10\x01\x12\x0b\n\x07\x43OUNTER\x10\x02')



_MESSAGEEVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='MessageEvent.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASIC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COUNTER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=193,
  serialized_end=241,
)


_MESSAGEEVENT_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='MessageEvent.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MessageEvent.Event.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MessageEvent.Event.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MessageEvent.Event.timestamp', index=2,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arg', full_name='MessageEvent.Event.arg', index=3,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=191,
)

_MESSAGEEVENT = _descriptor.Descriptor(
  name='MessageEvent',
  full_name='MessageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys_id', full_name='MessageEvent.sys_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='MessageEvent.event', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGEEVENT_EVENT, ],
  enum_types=[
    _MESSAGEEVENT_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=241,
)

_MESSAGEEVENT_EVENT.fields_by_name['type'].enum_type = _MESSAGEEVENT_EVENTTYPE
_MESSAGEEVENT_EVENT.containing_type = _MESSAGEEVENT;
_MESSAGEEVENT.fields_by_name['event'].message_type = _MESSAGEEVENT_EVENT
_MESSAGEEVENT_EVENTTYPE.containing_type = _MESSAGEEVENT;
DESCRIPTOR.message_types_by_name['MessageEvent'] = _MESSAGEEVENT

class MessageEvent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Event(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MESSAGEEVENT_EVENT

    # @@protoc_insertion_point(class_scope:MessageEvent.Event)
  DESCRIPTOR = _MESSAGEEVENT

  # @@protoc_insertion_point(class_scope:MessageEvent)


# @@protoc_insertion_point(module_scope)
